"""empty message

Revision ID: 151d6d25be16
Revises: 5e352cc76d16
Create Date: 2020-08-21 16:38:59.387656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151d6d25be16'
down_revision = '5e352cc76d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.alter_column('artists', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'artists', ['facebook_link'])
    op.create_unique_constraint(None, 'artists', ['website_link'])
    op.create_unique_constraint(None, 'artists', ['phone'])
    op.create_unique_constraint(None, 'artists', ['name'])
    op.drop_column('artists', 'seeking_performance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_performance', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    op.alter_column('artists', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
