"""empty message

Revision ID: 5e352cc76d16
Revises: 4a8ccf105c8c
Create Date: 2020-08-21 11:06:00.846117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e352cc76d16'
down_revision = '4a8ccf105c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.create_unique_constraint(None, 'venues', ['website_link'])
    op.create_unique_constraint(None, 'venues', ['facebook_link'])
    op.create_unique_constraint(None, 'venues', ['name'])
    op.create_unique_constraint(None, 'venues', ['address'])
    op.create_unique_constraint(None, 'venues', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'venues', type_='unique')
    op.alter_column('venues', 'genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###
