"""empty message

Revision ID: a3e151b1155f
Revises: 143570a936f7
Create Date: 2020-08-21 18:12:33.338281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e151b1155f'
down_revision = '143570a936f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
