"""empty message

Revision ID: c7dde1f76c4f
Revises: 151d6d25be16
Create Date: 2020-08-21 16:53:15.316515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dde1f76c4f'
down_revision = '151d6d25be16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_website_link_key', 'artists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('artists_website_link_key', 'artists', ['website_link'])
    # ### end Alembic commands ###
